spring.application.name=producer
server.port=8088

# Datasource Configuration (PostgreSQL)
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.url=jdbc:postgresql://localhost:8080/user

# HikariCP Configuration
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.idle-timeout=30000

# Logging Configuration (See logback-spring.xml for detailed configuration)

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Springdoc OpenAPI Configuration
springdoc.api-docs.path=/api-docs-json
springdoc.swagger-ui.path=/swagger
springdoc.api-docs.enabled=true

# Kafka Configuration
kafka.bootstrap-servers=localhost:8080
kafka.topic.sales-transaction=sales-transaction-{nama}